# https://developers.home-assistant.io/docs/apps/configuration#build-options
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
args:
  BUILD_VERSION: 1.4.0
